### PR TITLE
Neoformit patch 1

### PR DESCRIPTION
**Pull request by neoformit**
@eancelet
- Docker container simplified by building upon `rocker/shiny`
- Fixed some minor typos
- Rebuilt container and test run on my machine - working ok

### CODE REVIEW

**Comment by eancelet** [comment]
I will let Lain review. She is more qualified than me.  
Once this is merged, I'll update the image on duckerhub (I could also use github actions for that).

**Comment by Lain-inrae** [comment]
Hello!
Sorry I was on holidays ><
Thank you @neoformit , its more simple with rocker, that's true. And thank you for the syntax corrections!

**Comment by neoformit** [comment]
Thanks Lain! @eancelet are you able to update the Docker Hub and merge [the PR to gxit-tuto-dev](https://github.com/eancelet/training-material/pull/10)?

**Comment by eancelet** [comment]
Thank you both.  
I've updated the Docker Hub image and merged the PR.   
I'll update the PR to the GTN repo soon.

**Pull request merged**
